#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Thu Apr  9 13:18:10 2015
#

import wx,subprocess

# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class Gui(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: Gui.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.Start = wx.Button(self, wx.ID_ANY, _("Start"))
        self.Restart = wx.Button(self, wx.ID_ANY, _("Restart"))
        self.Stop = wx.Button(self, wx.ID_ANY, _("Stop"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.start, self.Start)
        self.Bind(wx.EVT_BUTTON, self.restart, self.Restart)
        self.Bind(wx.EVT_BUTTON, self.stop, self.Stop)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: Gui.__set_properties
        self.SetTitle(_("frame_1"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: Gui.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_1.Add(self.Start, 26, 0, 0)
        sizer_1.Add(self.Restart, 0, 0, 0)
        sizer_1.Add(self.Stop, 0, 0, 0)
        self.SetSizer(sizer_1)
        sizer_1.Fit(self)
        self.Layout()
        # end wxGlade

    def start(self, event):  # wxGlade: Gui.<event_handler>
        subprocess.Popen(['sudo', 'service', 'apache2','start']).communicate()
        

    def restart(self, event):  # wxGlade: Gui.<event_handler>
        subprocess.Popen(['sudo','service','apache2', 'restart']).communicate()

    def stop(self, event):  # wxGlade: Gui.<event_handler>
        subprocess.Popen(['sudo', 'service', 'apache2', 'stop']).communicate()

# end of class Gui
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = Gui(None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()
